# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a59ec78483a691997015aba47cc838cd39247402e1f3c80c0997b1e86f36743b25d542680ffbccb92a90bdef42838056de9767fcf004f97a18f25d6a9d13c9d

test:
  secret_key_base: ac920fecaa14d6e6eb7b256e7ae957cbdff25b76f1649ab3bfd2c502194ac191a1ab0eb80285fdf6f0319241c22d739cc8869b3f21a24330ad197707fb32840d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
